FORMAT: 1A
HOST: http://itas.apiary.io/
VERSION: 1.0

# Client ECTP

This collection of end points are specific to ECTP

# Group Finance

## Invoice Bank Accounts [/ITAS/ClientFunctions/Finance/{TradingEntityId}/InvoiceBankAccount]
Account details for Banks nominated during the Invoicing process. As such requires nomination of the Trading Entity in the URI.

### InvoiceBankAccount Lookup [GET]


# Group Data Functions

## Report Export Request [/ITAS/ClientFunctions/Data/Service100Export/]

### ReportExportRequest [POST]
Reporting extract request specific to end of day off-system reconciliation processes. <br />
This endpoint initialises the export of data to three tables: • GPLRep P&L, • GPLRep Valuation and • Trade Data (derived from phys01).

Proposed Request value of ‘InitiateExport’ to segregate from potential futures variations. <br />
DateToProcess will represent the requested ‘close of business’ day in datetime format which will be used as part of the verification procedure.<br />



